name: left4dead2dedicatedserverarm

volumes:
  l4d2-data:
  steamcmd-data:
  steam-home:

x-game-server: &game-server
  image: left4dead2dedicatedserverarm
  depends_on:
    l4d2-init:
      condition: service_completed_successfully
  volumes:
    - l4d2-data:/home/admin/app/l4d2server
  restart: unless-stopped

services:
  l4d2-init:
    image: left4dead2dedicatedserverarm
    build: .
    container_name: l4d2-init
    environment:
      L4D2_MODE: init
      STEAM_USERNAME: ${STEAM_USERNAME:-}
    volumes:
      - l4d2-data:/home/admin/app/l4d2server
      - steamcmd-data:/home/admin/app/steamcmd
      - steam-home:/home/admin/Steam
    restart: "no"

  l4d2-versus:
    <<: *game-server
    container_name: l4d2-versus
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
    environment:
      L4D2_PORT: "27015"
      L4D2_MAXPLAYERS: "8"
      L4D2_MAP: "c5m1_waterfront versus"
      L4D2_GAMETYPES: versus
      L4D2_GAMEMODE: versus
      L4D2_ARGS: ""
  
  l4d2-survivalversus:
    <<: *game-server
    container_name: l4d2-survivalversus    
    ports:
      - "27017:27017/udp"
      - "27017:27017/tcp"
    environment:
      L4D2_PORT: "27017"
      L4D2_MAXPLAYERS: "8"
      L4D2_MAP: "c5m2_park mutation15"
      L4D2_GAMETYPES: mutation15
      L4D2_GAMEMODE: mutation15
      L4D2_ARGS: ""

  l4d2-coop:
    <<: *game-server
    container_name: l4d2-coop    
    ports:
      - "27019:27019/udp"
      - "27019:27019/tcp"
    environment:
      L4D2_PORT: "27019"
      L4D2_MAXPLAYERS: "8"
      L4D2_MAP: "c5m1_waterfront coop"
      L4D2_GAMETYPES: coop
      L4D2_GAMEMODE: coop
      L4D2_ARGS: ""

  l4d2-scavenge:
    <<: *game-server
    container_name: l4d2-scavenge
    ports:
      - "27021:27021/udp"
      - "27021:27021/tcp"
    environment:
      L4D2_PORT: "27021"
      L4D2_MAXPLAYERS: "8"
      L4D2_MAP: "c8m5_rooftop scavenge"
      L4D2_GAMETYPES: scavenge
      L4D2_GAMEMODE: scavenge
      L4D2_ARGS: ""

  l4d2-survival:
    <<: *game-server
    container_name: l4d2-survival
    ports:
      - "27023:27023/udp"
      - "27023:27023/tcp"
    environment:
      L4D2_PORT: "27023"
      L4D2_MAXPLAYERS: "8"
      L4D2_MAP: "c5m2_park survival"
      L4D2_GAMETYPES: survival
      L4D2_GAMEMODE: survival
      L4D2_ARGS: ""
